--- #YAML:1.0
name:                Devel-Events
version:             0.05
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Moose:                         0.33
    MooseX::AttributeHelpers:      0.03
    Set::Object:                   0
    Test::use::ok:                 0
    Time::HiRes:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
